### ISSUE TITLE
Design database diagrams

### ISSUE THREAD

**Issue by kraleppa** [agh-docker-monitoring/dockiera-app#18]
We are having two database in the system (inlfux & RDBMS) we need to figure out what data should be stored in which databse.

In influx:
How many and what buckets do we need (at least 2 - for alerts and datapoints, we might tag every datapoint with the host name or id)

In RDBMS
What should we store (at least info about hosts + we need to store alerts rules)

We need good looking and precisie diagram for every db

**Comment by Ilargi12** [comment]
From branch backend-main -> create new branch -> Add diagrams as a png -> Create PR
