### ISSUE TITLE
Introduce logging

### ISSUE THREAD

**Issue by jakubsolecki** [agh-docker-monitoring/dockiera-app#43]
For the purpose of better tracing and debugging 

eg. SLF4J

**Comment by kraleppa** [comment]
@jakubsolecki isn't it done?
[link](https://github.com/agh-docker-monitoring/dockiera-app/blob/main/backend/src/main/kotlin/pl/edu/agh/dockerbuddy/controller/exceptionhandler/ExceptionHandler.kt)

**Comment by jakubsolecki** [comment]
@kraleppa we can consider [it](https://github.com/agh-docker-monitoring/dockiera-app/blob/main/backend/src/main/kotlin/pl/edu/agh/dockerbuddy/controller/exceptionhandler/ExceptionHandler.kt) as a start of this task and guide for future. It would be nice to add messages when metrics arrive and when they are processed

**Comment by kraleppa** [comment]
ok so let's leave it here for now

**Comment by jakubsolecki** [comment]
https://github.com/agh-docker-monitoring/dockiera-app/pull/58
