### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by kraleppa** [agh-docker-monitoring/dockiera-app#88]
We need to document API 
A review of the SWAGGER is needed

https://www.baeldung.com/swagger-2-documentation-for-spring-rest-api

**Comment by jakubsolecki** [comment]
Swagger UI is available under `/swagger-ui/` while same info in JSON format is under `/api-docs`

**Comment by jakubsolecki** [comment]
There was also observed issue where UI stopped working and the only working solution was to remove `swagger` and `springfox` form local meven repo (`.m2/repository/io/`) and download them again.
