### ISSUE TITLE
Test connection between agent and backend

### ISSUE THREAD

**Issue by kraleppa** [agh-docker-monitoring/dockiera-app#89]
Make sure everything is working and others.

**Comment by Ilargi12** [comment]
![image.png](https://images.zenhubusercontent.com/60b7dbeb65124f043b44b352/6a94af8c-5567-4cdd-a02d-80313921d8c0)

**Comment by Ilargi12** [comment]
Frontend working properly

**Comment by Ilargi12** [comment]
Backend working properly

**Comment by Ilargi12** [comment]
Influx working properly

**Comment by Ilargi12** [comment]
Normal agent working properly. Mock agent gets 500 HTTP errors.
